/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CacaAoTesouroRouteImport } from './routes/caca-ao-tesouro'
import { Route as IndexRouteImport } from './routes/index'

const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CacaAoTesouroRoute = CacaAoTesouroRouteImport.update({
  id: '/caca-ao-tesouro',
  path: '/caca-ao-tesouro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caca-ao-tesouro': typeof CacaAoTesouroRoute
  '/games': typeof GamesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caca-ao-tesouro': typeof CacaAoTesouroRoute
  '/games': typeof GamesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caca-ao-tesouro': typeof CacaAoTesouroRoute
  '/games': typeof GamesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/caca-ao-tesouro' | '/games'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/caca-ao-tesouro' | '/games'
  id: '__root__' | '/' | '/caca-ao-tesouro' | '/games'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CacaAoTesouroRoute: typeof CacaAoTesouroRoute
  GamesRoute: typeof GamesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caca-ao-tesouro': {
      id: '/caca-ao-tesouro'
      path: '/caca-ao-tesouro'
      fullPath: '/caca-ao-tesouro'
      preLoaderRoute: typeof CacaAoTesouroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CacaAoTesouroRoute: CacaAoTesouroRoute,
  GamesRoute: GamesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
